name: NDK build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'tag name'
        required: true
      bs_version:
        description: 'bs version'
        required: true
  pull_request:
    branches:
        - 'master'
        - 'main'
        - 'dev/*'
        - 'feat/*'
        - 'fix/*'

env:
    module_id: sabertailor
    qmod_name: SaberTailor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true

    - uses: seanmiddleditch/gha-setup-ninja@v3

    # Use canary NDK to avoid lesser known compile bugs
    - name: Setup canary NDK
      id: setup-ndk
      uses: ./.github/actions/canary-ndk

    - name: Create ndkpath.txt
      run: |
        echo ${{ steps.setup-ndk.outputs.ndk-path }} > ${GITHUB_WORKSPACE}/ndkpath.txt
        cat ${GITHUB_WORKSPACE}/ndkpath.txt

    # get version from pushed tag
    - name: Extract version
      if: startsWith(github.ref, 'refs/tags/v')
      id: version
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}" >> ${GITHUB_OUTPUT}
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> ${GITHUB_OUTPUT}

    - name: Setup qpm
      uses: Fernthedev/qpm-action@main
      with:
        workflow_token: ${{ secrets.GITHUB_TOKEN }}
        restore: true
        cache: true
        publish: false

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}
        qpm qmod manifest
        pwsh -Command ./build.ps1
    - name: Create Qmod
      run: |
        pwsh -Command ./buildQMOD.ps1 ${{ env.qmod_name }}_${{ github.event.inputs.version }}

    - name: Get Library Name
      id: libname
      run: |
        cd ./build/
        pattern="lib${module_id}*.so"
        files=( $pattern )
        echo "NAME=${files[0]}" >> ${GITHUB_OUTPUT}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.libname.outputs.NAME }}
        path: ./build/${{ steps.libname.outputs.NAME }}
        if-no-files-found: error

    - name: Upload qmod artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.qmod_name}}.qmod
        path: ./${{ env.qmod_name }}_${{ github.event.inputs.version }}.qmod
        if-no-files-found: error

    # if we had a tag, we should make a release
    - name: Upload release artifacts
      if: ${{ github.event_name == 'workflow_dispatch' }}
      id: upload_file_release
      uses: softprops/action-gh-release@v0.1.15
      with:
        name: Saber Tailor ${{ github.event.inputs.version }} for Beat Saber ${{ github.event.inputs.bs_version }} 
        tag_name: ${{ github.event.inputs.version }}
        draft: true
        generate_release_notes: true
        files: |
          ./build/${{ steps.libname.outputs.NAME }}
          ./build/debug_${{ steps.libname.outputs.NAME }}
          ./${{ env.qmod_name }}_${{ github.event.inputs.version }}.qmod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
